package com.example.classlist;

import java.util.HashMap;


public class DepartmentCodes {
    public static final String[] abbreviations = {"ACCT", "ACSCI", "ADVRT", "AER E", "AF AM", "A B E", "AGEDS", "AGRON", "AFAS", "AM IN", "ASL", "A ECL", "AN S", "ANTHR", "AESHM", "A M D", "ARABC", "ARCH", "ARTED", "ART H", "ASTRO", "A TR", "ATH", "BBMB", "BCBIO", "BCB", "BPM I", "BIOL", "B M E", "B M S", "BUSAD", "CH E", "CHEM", "CHIN", "C E", "CL ST", "CMDIS", "COMST", "C R P", "C DEV", "CPR E", "COM S", "CON E", "C J", "CYBSC", "CYB E", "CPS", "DANCE", "DS", "DES", "DSN S", "DIET", "E C P", "EEB", "EEOB", "ECON", "EDUC", "EDADM", "EL PS", "E E", "ENGR", "E M", "ENGL", "ENT", "ENTSP", "ENV E", "ENSCI", "ENV S", "EVENT", "FCEDS", "FFP", "FIN", "FS HN", "FOR", "FRNCH", "GEN", "GENET", "GDCB", "GEOL", "GER", "GERON", "GLOBE", "GR ST", "ARTGR", "H S", "HCM", "HG ED", "HIST", "HON", "HORT", "HSP M", "HCI", "HD FS", "H SCI", "IMBIO", "IND D", "I E", "ARTIS", "IGS", "ARTID", "INTST", "JL MC", "KIN", "L A", "LATIN", "LD ST", "L L S", "L TM", "LAS", "LIB", "LING", "MGMT", "MIS", "MKT", "MAT E", "M S E", "MATH", "M E", "MTEOR", "MICRO", "M S", "MCDB", "MUSIC", "NREM", "N S", "NEURO", "NRS", "NUTRS", "OTS", "PERF", "PHIL", "PHYS", "PLBIO", "PL P", "POL S", "PORT", "PSYCH", "P R", "RELIG", "RESEV", "RUS", "STB", "SOC", "S E", "SPAN", "SP ED", "SP CM", "STAT", "SCM", "SUSAG", "SUS E", "TSM", "THTRE", "TOX", "TRANS", "US LS", "U ST", "URB D", "VDPAM", "V C S", "V MPM", "V PTH", "WESEP", "WISE", "WGS", "W F S", "WLC", "YTH"};
    public static final String[] fullNames = {"ACCOUNTING", "ACTUARIAL SCIENCE", "ADVERTISING", "AEROSPACE ENGINEERING", "AFRICAN AND AFRICAN AMERICAN STUDIES", "AGRICULTURAL AND BIOSYSTEMS ENGINEERING", "AGRICULTURAL EDUCATION & STUDIES", "AGRONOMY", "AIR FORCE AEROSPACE STUDIES", "AMERICAN INDIAN STUDIES", "AMERICAN SIGN LANGUAGE", "ANIMAL ECOLOGY", "ANIMAL SCIENCE", "ANTHROPOLOGY", "APPAREL, EVENTS, AND HOSPITALITY MANAGEM", "APPAREL, MERCHANDISING, AND DESIGN", "ARABIC", "ARCHITECTURE", "ART EDUCATION", "ART HISTORY", "ASTRONOMY & ASTROPHYSICS", "ATHLETIC TRAINING", "ATHLETICS", "BIOCHEM, BIOPHYSICS & MOLECULAR BIO", "BIOINFORMATICS & COMPUTATIONAL BIOL-UG", "BIOINFORMATICS AND COMPUTATIONAL BIOL", "BIOLOGICAL/PRE-MEDICAL ILLUSTRATION", "BIOLOGY", "BIOMEDICAL ENGINEERING", "BIOMEDICAL SCIENCES", "BUSINESS ADMINISTRATION", "CHEMICAL ENGINEERING", "CHEMISTRY", "CHINESE", "CIVIL ENGINEERING", "CLASSICAL STUDIES", "COMMUNICATION DISORDERS", "COMMUNICATION STUDIES", "COMMUNITY & REGIONAL PLANNING", "COMMUNITY DEVELOPMENT", "COMPUTER ENGINEERING", "COMPUTER SCIENCE", "CONSTRUCTION ENGINEERING", "CRIMINAL JUSTICE", "CYBER SECURITY", "CYBER SECURITY ENGINEERING", "CYBER-PHYSICAL SYSTEMS", "DANCE", "DATA SCIENCE", "DESIGN", "DESIGN STUDIES", "DIETETICS", "EARLY CHILDCARE EDUCATION AND PROGRAMMIN", "ECOLOGY & EVOLUTIONARY BIOLOGY", "ECOLOGY, EVOLUTION & ORGANISMAL BIOL", "ECONOMICS", "EDUCATION", "EDUCATIONAL ADMINISTRATION", "EDUCATIONAL LEADERSHIP & POLICY ST", "ELECTRICAL ENGINEERING", "ENGINEERING", "ENGINEERING MECHANICS", "ENGLISH", "ENTOMOLOGY", "ENTREPRENEURSHIP", "ENVIRONMENTAL ENGINEERING", "ENVIRONMENTAL SCIENCE", "ENVIRONMENTAL STUDIES", "EVENT MANAGEMENT", "FAMILY & CONSUMER SCIENCES ED & STUDIES", "FAMILY FINANCIAL PLANNING", "FINANCE", "FOOD SCIENCE & HUMAN NUTRITION", "FORESTRY", "FRENCH", "GENETICS", "GENETICS - INTERDISCIPLINARY", "GENETICS, DEVELOPMENT & CELL BIOL", "GEOLOGY", "GERMAN", "GERONTOLOGY", "GLOBAL RESOURCE SYSTEMS", "GRADUATE STUDIES", "GRAPHIC DESIGN", "HEALTH STUDIES", "HEALTHCARE MANAGEMENT", "HIGHER EDUCATION", "HISTORY", "HONORS", "HORTICULTURE", "HOSPITALITY MANAGEMENT", "HUMAN COMPUTER INTERACTION", "HUMAN DEVELOPMENT & FAMILY STUDIES", "HUMAN SCIENCES", "IMMUNOBIOLOGY", "INDUSTRIAL DESIGN", "INDUSTRIAL ENGINEERING", "INTEGRATED STUDIO ARTS", "INTERDISCIPLINARY GRADUATE STUDIES", "INTERIOR DESIGN", "INTERNATIONAL STUDIES", "JOURNALISM & MASS COMMUNICATION", "KINESIOLOGY", "LANDSCAPE ARCHITECTURE", "LATIN", "LEADERSHIP STUDIES", "LEARNING AND LEADERSHIP SCIENCES", "LEARNING TEAM", "LIBERAL ARTS & SCIENCES", "LIBRARY", "LINGUISTICS", "MANAGEMENT", "MANAGEMENT INFORMATION SYSTEMS", "MARKETING", "MATERIALS ENGINEERING", "MATERIALS SCIENCE & ENGINEERING", "MATHEMATICS", "MECHANICAL ENGINEERING", "METEOROLOGY", "MICROBIOLOGY", "MILITARY SCIENCE", "MOLECULAR CELLULAR DEV BIOLOGY", "MUSIC", "NATURAL RESOURCE ECOLOGY AND MGMT", "NAVAL SCIENCE", "NEUROSCIENCE", "NURSING", "NUTRITIONAL SCIENCES", "ORGANIZATION FOR TROPICAL STUDIES", "PERFORMING ARTS", "PHILOSOPHY", "PHYSICS", "PLANT BIOLOGY", "PLANT PATHOLOGY", "POLITICAL SCIENCE", "PORTUGUESE", "PSYCHOLOGY", "PUBLIC RELATIONS", "RELIGIOUS STUDIES", "RESEARCH & EVALUATION", "RUSSIAN", "SEED TECHNOLOGY AND BUSINESS", "SOCIOLOGY", "SOFTWARE ENGINEERING", "SPANISH", "SPECIAL EDUCATION", "SPEECH COMMUNICATION", "STATISTICS", "SUPPLY CHAIN MANAGEMENT", "SUSTAINABLE AGRICULTURE", "SUSTAINABLE ENVIRONMENTS", "TECHNOLOGY SYSTEMS MANAGEMENT", "THEATRE", "TOXICOLOGY", "TRANSPORTATION", "U.S. LATINO/A STUDIES", "UNIVERSITY STUDIES", "URBAN DESIGN", "VET DIAGNOSTIC & PRODUCTION AN MED", "VETERINARY CLINICAL SCIENCES", "VETERINARY MICROBIOLOGY & PREV MED", "VETERINARY PATHOLOGY", "WIND ENERGY SCIENCE, ENGINEERING AND POL", "WISE", "WOMEN'S AND GENDER STUDIES", "WORLD FILM STUDIES", "WORLD LANGUAGES AND CULTURES", "YOUTH"};

    private static HashMap<String, String> shortToLong;
    private static HashMap<String, String> longToShort;

    private static boolean isMapped = false;

    public static String shortToLong(String abbreviation) {
        init();
        return shortToLong.get(abbreviation);
    }

    public static String longToShort(String fullName) {
        init();
        return longToShort.get(fullName);
    }

    private static void init() {
        if (!isMapped) {
            shortToLong = new HashMap<>();

            for (int i = 0; i < abbreviations.length; i++)
                shortToLong.put(abbreviations[i], fullNames[i]);

            longToShort = new HashMap<>();

            for (int i = 0; i < fullNames.length; i++)
                longToShort.put(fullNames[i], abbreviations[i]);

            isMapped = true;
        }
    }
}
