POST http://localhost:8080/user/create
Content-Type: application/json

{
  "username": "dq",
  "authenticationMethod": "plaintext",
  "authenticationData": "cool"
}

###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "dq"
}

###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "dq",
  "authenticationMethod": "plaintext",
  "authenticationData": "cool"
}

###
GET http://localhost:8080/onlineUsers

###
POST http://localhost:8080/schedule
Content-Type: application/json

{
  "name": "testschedule",
  "user": {
    "username": "dq"
  },
  "sections": [
    5560,
    5560
  ]
}

###
GET http://localhost:8080/onlineUsers

###
PUT http://localhost:8080/user/manage
Content-Type: application/json

{
  "username": "dq",
  "authenticationMethod": "plaintext",
  "authenticationData": "cool",
  "userContact": {
    "email": "dq@gmail.com",
    "phone": "27"
  }
}
###
POST http://localhost:8080/review
Content-Type: application/json

{
  "username": "hax",
  "classId": 1530,
  "difficulty": 2.71828,
  "text": "that's what she said"
}
###
